import {
  AlignLeft,
  AtSign,
  Calendar,
  CheckSquare,
  ChevronDownSquare,
  CircleDot,
  Gauge,
  Hash,
  Heading,
  type LucideIcon,
  Phone,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Star,
  ThumbsUp,
  Type,
} from 'lucide-react';
import type { QuestionType } from '@ff/form-schema';

export const QUESTION_ICONS: Record<QuestionType, LucideIcon> = {
  single_choice: CircleDot,
  multi_choice: CheckSquare,
  dropdown: ChevronDownSquare,
  yes_no: ThumbsUp,
  short_text: Type,
  long_text: AlignLeft,
  number: Hash,
  date: Calendar,
  email: AtSign,
  phone: Phone,
  consent: ShieldCheck,
  rating: Star,
  emoji: Smile,
  nps: Gauge,
  slider: SlidersHorizontal,
  section: Heading,
};
