/**
 * Export the local PGlite database as one SQL script that recreates the same rows in another
 * PostgreSQL database (used to move local/demo data into Supabase).
 *
 *   npm run export:sql -w api      (stop the API first)
 *
 * Output: api/data/export.sql — git-ignored, because it contains the admin password hash and
 * visitor answers. Rows are loaded with jsonb_populate_recordset, so types round-trip exactly.
 * Admin sessions and pairing codes are deliberately not exported.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { openDb } from './db';

const TABLES: Array<{ name: string; order: string }> = [
  { name: 'tenant', order: 'created_at' },
  { name: 'admin_user', order: 'created_at' },
  { name: 'form', order: 'created_at' },
  { name: 'form_version', order: 'created_at' },
  { name: 'device', order: 'created_at' },
  { name: 'submission', order: 'received_at' },
  { name: 'answer', order: 'submission_id' },
  { name: 'asset', order: 'created_at' },
  { name: 'audit_log', order: 'id' },
];

const db = await openDb(resolve(import.meta.dirname, '..', process.env.DATA_DIR ?? 'data/pgdata'));
try {
  const parts: string[] = [
    '-- Generated by api/src/export-sql.ts. Run against an EMPTY, migrated database.',
    'begin;',
  ];
  for (const t of TABLES) {
    const { rows } = await db.query<{ data: unknown }>(`select coalesce(jsonb_agg(x order by x.${t.order}), '[]'::jsonb) as data from ${t.name} x`);
    let json = JSON.stringify(rows[0]!.data);
    if (t.name === 'form') {
      // form.live_version_id references form_version, which is inserted afterwards.
      json = JSON.stringify((rows[0]!.data as Array<Record<string, unknown>>).map((f) => ({ ...f, live_version_id: null })));
    }
    if (json.includes('$ffjson$')) throw new Error('unexpected delimiter in data');
    parts.push(`insert into ${t.name} select * from jsonb_populate_recordset(null::${t.name}, $ffjson$${json}$ffjson$);`);
    if (t.name === 'form_version') {
      const forms = await db.query<{ id: string; live_version_id: string | null }>('select id, live_version_id from form');
      for (const f of forms.rows) {
        if (f.live_version_id) parts.push(`update form set live_version_id = '${f.live_version_id}' where id = '${f.id}';`);
      }
    }
    console.log(`  ${t.name}: ${(rows[0]!.data as unknown[]).length} rows`);
  }
  parts.push(`select setval(pg_get_serial_sequence('audit_log', 'id'), coalesce((select max(id) from audit_log), 1));`);
  parts.push('commit;');
  const out = resolve(import.meta.dirname, '../data/export.sql');
  writeFileSync(out, parts.join('\n') + '\n');
  console.log(`Wrote ${out}`);
} finally {
  await db.close();
}
